In [1]:
import os
os.environ['OPENCV_IO_MAX_IMAGE_PIXELS']=str(2**64)
import cv2
import matplotlib.pyplot as plt
import numpy as np 
import os
from numpy import linalg
import math
import itertools

# Zhang's

In [2]:
# Function to convert the Rotation Matrix into the Euler Angles
def eulerAnglesToRotationMatrix(theta) :
    R_x = np.array([[1,0,0],[0,math.cos(theta[0]),-math.sin(theta[0])],[0,math.sin(theta[0]), math.cos(theta[0])]])
    R_y = np.array([[math.cos(theta[1]),0,math.sin(theta[1])],[0,1,0],[-math.sin(theta[1]),0,math.cos(theta[1])]])             
    R_z = np.array([[math.cos(theta[2]),-math.sin(theta[2]),0],[math.sin(theta[2]),math.cos(theta[2]),0],[0,0,1]])
    R = np.dot(R_z,np.dot(R_y,R_x))
    return R

In [3]:
I1 = cv2.imread('HandsOn/IMG_1.jpg')
# plt.figure()
# plt.imshow(I1[...,::-1])
# ret, corners = cv2.findChessboardCorners(I1,(7,9))
ret, corners = cv2.findChessboardCorners(I1,(6,9))
corners = corners.reshape(-1,2)
print (corners.shape)
print (corners)

(51, 2)
[[ 694.   282.5]
 [ 473.5  283. ]
 [ 907.   283. ]
 [ 912.5  436.5]
 [ 689.5  438. ]
 [ 461.5  440. ]
 [ 685.5  604.5]
 [ 446.5  608. ]
 [ 918.5  600.5]
 [ 925.   781.5]
 [ 682.   790. ]
 [ 432.5  795. ]
 [ 677.5  992.5]
 [ 414.  1000.5]
 [ 931.5  982. ]
 [ 940.  1201.5]
 [ 672.5 1216.5]
 [ 396.  1231. ]
 [1162.5  772. ]
 [1180.   971.5]
 [1201.  1187.5]
 [1421.   959.5]
 [1452.5 1170.5]
 [1616.   762. ]
 [1655.   951.5]
 [1391.   767.5]
 [1699.  1154. ]
 [1885.5  942. ]
 [1938.5 1146.5]
 [2052.5  749.5]
 [2110.   933.5]
 [1837.5  755.5]
 [2173.  1136. ]
 [2329.   926. ]
 [2401.  1125. ]
 [2264.   742. ]
 [2203.5  573.5]
 [1999.5  579.5]
 [1952.   427. ]
 [1793.   582. ]
 [1754.   425.5]
 [1581.   587. ]
 [1716.   279.5]
 [1549.5  429.5]
 [1519.   281.5]
 [1319.5  281. ]
 [1366.   591. ]
 [1343.   429.5]
 [1145.5  595.5]
 [1131.5  434. ]
 [1117.   281.5]]


In [4]:
# x,y=np.meshgrid(range(7),range(9))
x,y=np.meshgrid(range(6),range(9))
world_points=np.hstack((x.reshape(54,1),y.reshape(54,1),np.zeros((54,1)))).astype(np.float32)
print(world_points)
## Correspondences
print (corners[0],'->',world_points[0])
print (corners[35],'->',world_points[35])

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]
 [5. 5. 0.]
 [0. 6. 0.]
 [1. 6. 0.]
 [2. 6. 0.]
 [3. 6. 0.]
 [4. 6. 0.]
 [5. 6. 0.]
 [0. 7. 0.]
 [1. 7. 0.]
 [2. 7. 0.]
 [3. 7. 0.]
 [4. 7. 0.]
 [5. 7. 0.]
 [0. 8. 0.]
 [1. 8. 0.]
 [2. 8. 0.]
 [3. 8. 0.]
 [4. 8. 0.]
 [5. 8. 0.]]
[694.  282.5] -> [0. 0. 0.]
[2264.  742.] -> [5. 5. 0.]


In [5]:
#Zhangs for first focus
_3d_points=[]
_2d_points=[]

for i in range(1,18):
    im=cv2.imread('HandsOn/IMG_' + str(i) + '.jpg')

#     ret, corners = cv2.findChessboardCorners(im, (7,9))
    ret, corners = cv2.findChessboardCorners(im, (6,9))

    if ret: #add points only if checkerboard was correctly detected:
        _2d_points.append(corners) #append current 2D points
        _3d_points.append(world_points) #3D points are always the same

# print(_3d_points)
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(_3d_points, _2d_points, (im.shape[1],im.shape[0]), None, None)

print('Reprojection Error:', ret)
print ('Camera Calibration Matrix:')
print(mtx)
print('Distortion Parameters:')
print(dist)
print('Rotation Vectors for the images are:')
print(rvecs)
print('Translation Vectors for the images are:')
print(tvecs)


Reprojection Error: 7.0221769747195255
Camera Calibration Matrix:
[[3.96427211e+03 0.00000000e+00 7.12999598e+02]
 [0.00000000e+00 3.89383471e+03 9.70953774e+01]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Parameters:
[[ 0.33522811 -1.54345096 -0.05022154 -0.04568572  2.50388462]]
Rotation Vectors for the images are:
[array([[-0.78744631],
       [-0.31037701],
       [ 2.21208199]]), array([[-1.14527378],
       [ 0.49620465],
       [ 0.62567945]]), array([[-0.82378429],
       [ 0.73108059],
       [ 1.41230556]]), array([[-0.81750913],
       [ 0.65045304],
       [ 1.36072661]]), array([[-0.45665153],
       [ 0.14677019],
       [ 1.30717843]]), array([[-1.03139328],
       [ 0.41638315],
       [ 1.65612428]]), array([[-1.08928162],
       [ 0.32416477],
       [ 0.50040699]]), array([[-1.03275491],
       [-0.61029319],
       [ 1.91567675]])]
Translation Vectors for the images are:
[array([[ 5.8533659 ],
       [ 6.7436951 ],
       [21.24956541]]), array([[ 5.

In [6]:
#Zhangs for second focus
I1 = cv2.imread('HandsOn/IM_1.jpg')
# plt.figure()
# plt.imshow(I1[...,::-1])
# ret, corners = cv2.findChessboardCorners(I1,(7,9))
ret, corners = cv2.findChessboardCorners(I1,(6,9))
corners = corners.reshape(-1,2)


x,y=np.meshgrid(range(6),range(9))
world_points=np.hstack((x.reshape(54,1),y.reshape(54,1),np.zeros((54,1)))).astype(np.float32)


_3d_points=[]
_2d_points=[]

for i in range(1,18):
    im=cv2.imread('HandsOn/IM_' + str(i) + '.jpg')
    print(i)

#     ret, corners = cv2.findChessboardCorners(im, (7,9))
    ret, corners = cv2.findChessboardCorners(im, (6,9))

    if ret: #add points only if checkerboard was correctly detected:
        _2d_points.append(corners) #append current 2D points
        _3d_points.append(world_points) #3D points are always the same

# print(_3d_points)
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(_3d_points, _2d_points, (im.shape[1],im.shape[0]), None, None)

print('Reprojection Error:', ret)
print ('Camera Calibration Matrix:')
print(mtx)
print('Distortion Parameters:')
print(dist)
print('Rotation Vectors for the images are:')
print(rvecs)
print('Translation Vectors for the images are:')
print(tvecs)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
Reprojection Error: 6.2155604983834145
Camera Calibration Matrix:
[[3.97513079e+03 0.00000000e+00 1.49470320e+03]
 [0.00000000e+00 4.04235256e+03 4.74789680e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Parameters:
[[-2.94077203e-01  3.13011031e+00  2.32278553e-03  1.36001178e-03
  -1.23929323e+01]]
Rotation Vectors for the images are:
[array([[-0.70734786],
       [ 0.43523084],
       [ 1.40234406]]), array([[-0.89613991],
       [-0.5366577 ],
       [ 2.14124214]]), array([[-0.93625293],
       [ 0.68864613],
       [ 1.34054301]]), array([[-1.07932552],
       [ 0.35150101],
       [ 0.55792969]]), array([[-0.88770888],
       [ 0.47412262],
       [ 1.28113684]]), array([[-0.9409666 ],
       [ 0.67762316],
       [ 1.31052297]]), array([[-1.06456634],
       [ 0.37416522],
       [ 0.81439179]]), array([[-1.23182631],
       [-0.11702556],
       [ 1.24204716]]), array([[-0.76156957],
       [ 0.70623079],
       [ 2.0

# DLT

In [29]:
#DLT
def DLT(corners,world_pt):
    M = []
    for i in range(8):
        X,Y,Z = world_pt[i,0],world_pt[i,1],world_pt[i,2]
        u,v = corners[i,0],corners[i,1]
        a_x = [-X,-Y,-Z,-1,0,0,0,0,u*X,u*Y,u*Z,u]
        a_y = [0,0,0,0,-X,-Y,-Z,-1,v*X,v*Y,v*Z,v]
        M.append(a_x)
        M.append(a_y)
    M = np.array(M)
    M = M.reshape(2*8,12)
    
    U,S,Vh = np.linalg.svd(M)
    L = Vh[-1,:] /Vh[-1,-1]
    
    #Camera projection matrix:
    P = L.reshape(3,4)
    print("Projection Matrix")
    print(P)
    
    H = P[0:3,0:3]
    h = P[:,-1]   
    
    H_inv = np.linalg.pinv(H)
    #projection center X0= -H_inv.h
    Proj_center = -1*np.matmul(H_inv,h)
    print("projection_center")
    print(Proj_center)
    
    #QR Decomposition of H_inv for getting rotation and calibration matrix 
    q, r = np.linalg.qr(H_inv)
    
    K = np.linalg.pinv(r)
    K = r/r[-1,-1]
    print("Camera Calibration matrix")
    print(K)
    
    print("Rotation matrix")
    Rot_mat = q.transpose()
    print(Rot_mat)
    
#     PX = np.matmul(P,world_pt[pt,:].reshape(4,1))
    error = 0
    for pt in range(8):
        PX = np.matmul(P,world_pt[pt,:].reshape(4,1))
        PX = PX/PX[-1,-1]
        error += (np.linalg.norm((corners[pt]-PX)))

    error = error/8
    print(error)
    return P

In [32]:
focus1 = cv2.imread('cubenew.jpeg')
# A=np.array(focus1)
# print(A)
#focus2 = cv2.imread('HandsOn_/Cube2.jpg')

img=cv2.resize(focus1,(1024,1024))

# world_pt=np.matrix([[0,2,2*6,1],[0,2,2*3,1],[0,2,0,1],[2*3,2,0,1],[2*6,2,3,1]]
# #                       [0,28*3,28*6,1],[0,28*3,28*3,1],[0,28*3,0,1],[28*3,28*3,0,1],[28*6,28*3,3,1],
# #                       [0,28*5,28*6,1],[0,28*5,28*3,1],[0,28*5,0,1],[28*3,28*5,0,1],[28*6,28*5,3,1],
# #                       [0,28*7,28*6,1],[0,28*7,28*3,1],[0,28*7,0,1],[28*3,28*7,0,1],[28*6,28*7,3,1]])

# corners = np.matrix([[627, 1908,1], [1136, 1829,1], [1549, 1764,1], [1926, 1829,1], [2413, 1922,1]]
# #             [1145, 2185,1], [1549, 2093,1], [1922, 2189,1], [2387, 2321,1], [688, 2685,1], [1145, 2523,1], 
# #             [1540, 2400,1], [1913, 2540,1], [2374, 2698,1], [706, 3032,1], [1158, 2856,1], [1544, 2707,1], 
# #             [1913, 2861,1], [2352, 3062,1]])

Pcam=np.matrix([[122,342,1],[522,534,1],[213,569,1],[510,739,1],[726,537,1],[830,329,1],[484,328,1],[464,184,1]])
Pworld=np.matrix([[3,0,0,1],[0,0,0,1],[3,0,3,1],[0,0,3,1],[0,3,3,1],[0,3,0,1],[1.5,1.5,0,1],[3,3,0,1]])

DLT(Pcam,Pworld)


# %matplotlib qt
plt.figure()
plt.imshow(img)                    

Projection Matrix
[[-1.28659556e+02  1.78069145e+02  6.83621294e+01  5.27150931e+02]
 [-4.78280484e+01 -4.24957389e+01  1.74666956e+02  5.41653424e+02]
 [ 5.75537096e-02  9.57109214e-02  1.49687309e-01  1.00000000e+00]]
projection_center
[-1.8592989  -2.66853575 -4.2594288 ]
Camera Calibration matrix
[[ 9.15616187e-04  1.85096461e-05 -5.31896099e-01]
 [ 0.00000000e+00  1.20819201e-03 -6.69418257e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Rotation matrix
[[-0.79942514  0.59620979 -0.07384665]
 [-0.51570446 -0.6179784   0.59342363]
 [ 0.30816935  0.51248082  0.80149552]]
1046.145858161171
